# Generated by Django 5.2.5 on 2025-09-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_userinfo_course_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='interest',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
