# Generated by Django 5.2.6 on 2025-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userinfo_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('instructor', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('language', models.CharField(max_length=50)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
